### ISSUE TITLE
Debian packaging with xor-gate/debpkg

### ISSUE THREAD

**Issue by xor-gate** [holocm/holo-build#12]
Hi,

I would like to let you know I have created a debian packaging library (not fully finished yet).
Maybe you find it useful https://github.com/xor-gate/debpkg.

Kind regards,
Jerry

**Comment by majewsky** [comment]
Nice project! Thanks for pointing it out for me. However, since my own dpkg implementation is working fine and not causing any maintenance burden, I do not see a need to replace it.
